export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const INCREASE_QUANTITY= 'INCREASE_QUANTITY';
export const CANCEL_ORDER= 'CANCEL_ORDER';
export const SHOW_TOTAL= 'SHOW_TOTAL';
export const CREATE_CUSTOMER_ORDER= 'CREATE_CUSTOMER_ORDER';
export const LOGOUT= 'LOGOUT';
